name = "seeder"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[[kv_namespaces]]
binding = "SEED_KV"
id = "90c9d3c056cb46aead373f3c18e33362"
preview_id = "90c9d3c056cb46aead373f3c18e33362"
